### ISSUE TITLE
Expose comment prefiix

### ISSUE THREAD

**Issue by neveenatik** [dkershner6/jest-coverage-commenter-action#169]
Hello @dkershner6 
What is your thoughts about exposing comment prefix to consumer to provide a way to customize the coverage comment.
Of course it is possible to do so with another action that would find and customize the comment body, but I think It would make this action more flexible and would save a couple of minutes 😉
For example if the consumer would like to indicate the minimal test coverage percentage before the result of the code coverage summary or add some link for documentation. 

Again if you like this idea I would be very happy to create a PR 🙂

**Comment by dkershner6** [comment]
I always thought this would likely be something someone would want someday, which is why I set it up as a variable that got used in the first place.

If you find it difficult to implement, or would like a dynamic prefix (like, it would change each run), we can change the prefix to a suffix (and change to check to use `endsWith`). We could make the suffix invisible using html comments `<!-- JEST_COVERAGE_SUFFIX! -->`

Have at it!
